# Generated by Django 5.0.14 on 2025-12-13 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador (Slug)')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual')),
                ('max_surveys', models.PositiveIntegerField(default=5, verbose_name='Máx. Encuestas Activas')),
                ('max_responses_per_survey', models.PositiveIntegerField(default=100, verbose_name='Máx. Respuestas por Encuesta')),
                ('includes_advanced_analysis', models.BooleanField(default=False, verbose_name='Incluye Análisis Avanzado')),
                ('includes_pdf_export', models.BooleanField(default=False, verbose_name='Incluye Exportación PDF/PPTX')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan SaaS',
                'verbose_name_plural': 'Planes SaaS',
            },
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PDF', 'PDF'), ('PPTX', 'PowerPoint')], default='PDF', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, help_text='Ruta local del archivo', max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, help_text='URL pública para descarga', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('past_due', 'Pago Pendiente')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicio')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin del Periodo Actual')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Cliente Pasarela')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Suscripción Pasarela')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.plan', verbose_name='Plan Actual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa / Consultora')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_onboarded', models.BooleanField(default=False, help_text='¿Ha completado el tour inicial?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
