# Generated by Django 5.0.14 on 2025-12-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan SaaS', 'verbose_name_plural': 'Planes SaaS'},
        ),
    ]
