# Generated by Django 5.0.14 on 2025-12-10 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_plan_options'),
        ('surveys', '0028_delete_analysissegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(help_text='Lista de correos destinatarios separados por coma', verbose_name='Destinatarios')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Frecuencia de Envío')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Última vez enviado')),
                ('include_charts', models.BooleanField(default=True, verbose_name='Incluir Gráficos')),
                ('include_raw_data', models.BooleanField(default=False, verbose_name='Incluir CSV Adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Encuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'ordering': ['-created_at'],
            },
        ),
    ]
