# Generated by Django 5.2.8 on 2025-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='objetivo_muestra',
            field=models.PositiveIntegerField(default=100, verbose_name='Sample Goal'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='es_obligatoria',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('text', 'Text response'), ('multiple-choice', 'Multiple choice'), ('satisfaction', 'Satisfaction scale (e.g., 1-10)'), ('nps', 'Net Promoter Score (NPS)')], default='text', max_length=20, verbose_name='Type'),
        ),
    ]
