# Generated by Django 5.2.8 on 2025-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_encuesta_descripcion_alter_encuesta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('finished', 'Finalizada')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='objetivo_muestra',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='es_obligatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('text', 'Respuesta de texto'), ('multiple-choice', 'Opción múltiple'), ('satisfaction', 'Escala de satisfacción (ej. 1-10)'), ('nps', 'Net Promoter Score (NPS)')], default='text', max_length=20),
        ),
    ]
