# Generated by Django 5.2.8 on 2025-11-12 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_encuesta_descripcion_alter_encuesta_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'Encuesta', 'verbose_name_plural': 'Encuestas'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'Opción de respuesta', 'verbose_name_plural': 'Opciones de respuesta'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('finished', 'Finalizada')], default='draft', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='objetivo_muestra',
            field=models.PositiveIntegerField(default=0, verbose_name='Objetivo de respuestas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Opción'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='es_obligatoria',
            field=models.BooleanField(default=False, verbose_name='Obligatoria'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=500, verbose_name='Texto de la pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('text', 'Respuesta de texto'), ('multiple-choice', 'Opción múltiple'), ('satisfaction', 'Escala de satisfacción (1-10)'), ('nps', 'Net Promoter Score (NPS)')], default='text', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anonima', models.BooleanField(default=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.encuesta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.respuestaencuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Pregunta',
                'verbose_name_plural': 'Respuestas de Pregunta',
                'unique_together': {('respuesta_encuesta', 'pregunta')},
            },
        ),
    ]
