# Generated by Django 5.2.8 on 2025-11-19 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_encuesta_options_alter_opcionrespuesta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'Answer Option', 'verbose_name_plural': 'Answer Options'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='respuestaencuesta',
            options={'verbose_name': 'Survey Response', 'verbose_name_plural': 'Survey Responses'},
        ),
        migrations.AlterModelOptions(
            name='respuestapregunta',
            options={'verbose_name': 'Question Response', 'verbose_name_plural': 'Question Responses'},
        ),
        migrations.AlterUniqueTogether(
            name='respuestapregunta',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='objetivo_muestra',
            field=models.PositiveIntegerField(default=0, verbose_name='Sample Goal'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='surveys.pregunta', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='opcionrespuesta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='surveys.encuesta', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='es_obligatoria',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número'), ('scale', 'Escala 1-10'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='anonima',
            field=models.BooleanField(default=False, verbose_name='Anonymous'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='surveys.encuesta', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.opcionrespuesta', verbose_name='Selected Option'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.pregunta', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='respuesta_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_pregunta', to='surveys.respuestaencuesta', verbose_name='Survey Response'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='valor_numerico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numeric Value'),
        ),
        migrations.AlterField(
            model_name='respuestapregunta',
            name='valor_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Text Value'),
        ),
    ]
