# Generated by Django 5.2.8 on 2025-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_encuesta_options_alter_opcionrespuesta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(default='General', help_text='Tema o categoría de la encuesta (ej. Marketing, Salud, Tecnología).', max_length=100, verbose_name='Category'),
        ),
    ]
