# Generated by Django 5.2.8 on 2025-11-22 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_encuesta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(default='General', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='respuestaencuesta',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
    ]
