# Generated by Django 5.2.8 on 2025-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_encuesta_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(db_index=True, default='General', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada')], db_index=True, default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número'), ('scale', 'Escala 1-10'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
