# Generated by Django 5.0.14 on 2025-11-27 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_add_composite_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['order'], 'verbose_name': 'Answer Option', 'verbose_name_plural': 'Answer Options'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={'verbose_name': 'Question Response', 'verbose_name_plural': 'Question Responses'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'verbose_name': 'Survey Response', 'verbose_name_plural': 'Survey Responses'},
        ),
        migrations.AddField(
            model_name='answeroption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Option Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número'), ('scale', 'Escala 1-10'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], db_index=True, max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='numeric_value',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Numeric Value'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.answeroption', verbose_name='Selected Option'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.surveyresponse', verbose_name='Survey Response'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='text_value',
            field=models.TextField(blank=True, null=True, verbose_name='Text Value'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sample_goal',
            field=models.PositiveIntegerField(default=0, verbose_name='Sample Goal'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada')], db_index=True, default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonymous'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
