# Generated by Django 5.x on 2025-12-01
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0013_add_delete_optimization_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.CharField(max_length=512, verbose_name='Ruta archivo CSV')),
                ('status', models.CharField(max_length=20, choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(null=True, blank=True)),
                ('survey', models.ForeignKey(to='surveys.Survey', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, verbose_name='Encuesta')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación de CSV',
                'verbose_name_plural': 'Importaciones de CSV',
                'db_table': 'surveys_importjob',
            },
        ),
    ]
