# Generated by Django 5.0.14 on 2025-12-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_create_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Indica si la encuesta fue importada desde CSV (no permite cambiar estado)', verbose_name='Is Imported'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
