# Generated by Django 5.0.14 on 2025-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_add_public_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'En Pausa'), ('closed', 'Cerrada')], db_index=True, default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
