# Generated by Django 5.0.14 on 2025-12-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_alter_survey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='survey_title',
            field=models.CharField(blank=True, help_text='Si está vacío, usa el nombre del archivo', max_length=255, null=True, verbose_name='Título personalizado de la encuesta'),
        ),
    ]
