# Generated by Django 5.0.14 on 2025-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_importjob_survey_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Nombre del archivo CSV subido por el usuario', max_length=255, null=True, verbose_name='Nombre original del archivo'),
        ),
    ]
