# Generated by Django 5.0.14 on 2025-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_add_original_filename_to_importjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número'), ('scale', 'Escala 1-10'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], db_column='column_type', db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
