# Generated by Django 5.0.14 on 2025-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_fix_db_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_analyzable',
            field=models.BooleanField(default=True, help_text='Indica si esta pregunta debe incluirse en los reportes estadísticos', verbose_name='Is Analyzable'),
        ),
    ]
