# Generated by Django 5.0.14 on 2025-12-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_question_is_analyzable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.CharField(max_length=512, verbose_name='Ruta archivo CSV')),
                ('original_filename', models.CharField(blank=True, help_text='Nombre del archivo físico subido', max_length=255, null=True, verbose_name='Nombre original')),
                ('survey_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título asignado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Filas Totales')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Filas Procesadas')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Log de Errores')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey', verbose_name='Encuesta Generada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'CSV Log',
                'verbose_name_plural': 'CSV Logs',
                'db_table': 'surveys_csvlog',
            },
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
