# Generated by Django 5.0.14 on 2025-12-08 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_csvlog_delete_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_analyzable',
            field=models.BooleanField(default=True, help_text='Indica si esta pregunta debe incluirse en los reportes estadísticos automáticos', verbose_name='Is Analyzable'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texto libre'), ('number', 'Número'), ('scale', 'Escala 1-10'), ('single', 'Opción única'), ('multi', 'Opción múltiple')], db_index=True, max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.CharField(max_length=512, verbose_name='Ruta archivo CSV')),
                ('original_filename', models.CharField(blank=True, help_text='Nombre del archivo CSV subido por el usuario', max_length=255, null=True, verbose_name='Nombre original del archivo')),
                ('survey_title', models.CharField(blank=True, help_text='Si está vacío, usa el nombre del archivo', max_length=255, null=True, verbose_name='Título personalizado de la encuesta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey', verbose_name='Encuesta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación de CSV',
                'verbose_name_plural': 'Importaciones de CSV',
                'db_table': 'surveys_importjob',
            },
        ),
        migrations.DeleteModel(
            name='CsvLog',
        ),
    ]
