# Generated by Django 5.0.14 on 2025-12-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_alter_question_is_analyzable_alter_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('structure', models.JSONField(help_text='Definición de preguntas y lógica', verbose_name='Estructura JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.question', verbose_name='Depende de la pregunta'),
        ),
        migrations.AddField(
            model_name='question',
            name='visible_if_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_in_questions', to='surveys.answeroption', verbose_name='Visible si selecciona'),
        ),
    ]
