# Generated by Django 5.0.14 on 2025-12-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_analysissegment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissegment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Segmento de Análisis', 'verbose_name_plural': 'Segmentos de Análisis'},
        ),
        migrations.AddField(
            model_name='analysissegment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysissegment',
            name='filters_criteria',
            field=models.JSONField(verbose_name='Criterios de Filtro'),
        ),
        migrations.AlterField(
            model_name='analysissegment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Segmento'),
        ),
        migrations.AlterField(
            model_name='analysissegment',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_segments', to='surveys.survey'),
        ),
    ]
