# Generated by Django 5.0.14 on 2025-12-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_alter_analysissegment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisSegment',
        ),
    ]
