# Generated by Django 5.0.14 on 2025-12-10 (restauración manual)
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):
    dependencies = [
        ('surveys', '0027_alter_analysissegment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Segmento')),
                ('filters_criteria', models.JSONField(verbose_name='Criterios de Filtro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_segments', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segmento de Análisis',
                'verbose_name_plural': 'Segmentos de Análisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
