# Generated by Django 5.0.14 on 2025-12-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_delete_analysissegment'),
        ('surveys', '0029_restore_analysissegment'),
    ]

    operations = [
    ]
