# Generated by Django 5.0.14 on 2025-12-13 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_merge_20251210_0840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissegment',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='analysissegment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='questionresponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='survey',
            name='survey_author_sequence_unique',
        ),
        migrations.RemoveIndex(
            model_name='answeroption',
            name='answeroption_question_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='survey_question_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_response_anon_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='user_response_date_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='surveys_que_survey__d73192_idx',
            old_name='survey_question_order_idx',
        ),
        migrations.RenameIndex(
            model_name='questionresponse',
            new_name='surveys_que_questio_909767_idx',
            old_name='qresponse_q_numeric_idx',
        ),
        migrations.RenameIndex(
            model_name='questionresponse',
            new_name='surveys_que_questio_37aaef_idx',
            old_name='qresponse_q_option_idx',
        ),
        migrations.RenameIndex(
            model_name='questionresponse',
            new_name='surveys_que_survey__8532e1_idx',
            old_name='qresponse_survey_q_idx',
        ),
        migrations.RenameIndex(
            model_name='surveyresponse',
            new_name='surveys_sur_survey__0b82f6_idx',
            old_name='survey_response_date_idx',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='question',
            name='demographic_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='visible_if_option',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='author_sequence',
        ),
        migrations.AddField(
            model_name='answeroption',
            name='value',
            field=models.CharField(blank=True, help_text='Valor interno para análisis (opcional)', max_length=50),
        ),
        migrations.AddField(
            model_name='importjob',
            name='error_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obligatoria'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='completion_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/csv/'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='processed_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='survey_title',
            field=models.CharField(blank=True, default='[Importación Antigua]', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importjob',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='is_analyzable',
            field=models.BooleanField(default=True, help_text='Incluir en reportes automáticos'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_demographic',
            field=models.BooleanField(default=False, help_text='Es dato demográfico (Edad, Género, etc.)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texto Corto'), ('textarea', 'Texto Largo'), ('number', 'Número'), ('single', 'Selección Única (Radio)'), ('multi', 'Selección Múltiple (Checkbox)'), ('select', 'Lista Desplegable'), ('scale', 'Escala (1-10 o 1-5)'), ('date', 'Fecha'), ('section', 'Sección / Encabezado')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.answeroption'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.surveyresponse'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría (Ej. HR, CX)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Es Importada'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='public_id',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sample_goal',
            field=models.IntegerField(default=0, help_text='0 = Sin límite', verbose_name='Meta de Respuestas'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('closed', 'Cerrada'), ('paused', 'Pausada')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['author', 'status'], name='surveys_sur_author__b7fbea_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['public_id'], name='surveys_sur_public__6cf75e_idx'),
        ),
        migrations.AlterModelTable(
            name='answeroption',
            table=None,
        ),
        migrations.AlterModelTable(
            name='importjob',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='questionresponse',
            table=None,
        ),
        migrations.AlterModelTable(
            name='survey',
            table=None,
        ),
        migrations.AlterModelTable(
            name='surveyresponse',
            table=None,
        ),
        migrations.DeleteModel(
            name='AnalysisSegment',
        ),
    ]
