# Generated by Django 5.0.14 on 2025-12-17 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_merge_20251210_0840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='survey_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='demographic_type',
            field=models.CharField(blank=True, choices=[('age', 'Edad'), ('gender', 'Género'), ('location', 'Ubicación'), ('occupation', 'Ocupación'), ('marital_status', 'Estado civil'), ('other', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_analyzable',
            field=models.BooleanField(default=True, verbose_name='Is Analyzable'),
        ),
        migrations.AlterField(
            model_name='question',
            name='visible_if_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visible_in_questions', to='surveys.answeroption'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='numeric_value',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.answeroption'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='surveys.surveyresponse'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='author_sequence',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Author Sequence'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='Indica si la encuesta fue importada desde CSV.', verbose_name='Is Imported'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Public ID'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnalysisSegment',
        ),
    ]
